const AREAS = [
  {
    city: "santiago",
    areas: [
      { id: 1, title: "Centro Histórico", value: "centro" },
      { id: 2, title: "Santa Isabel", value: "isabel" },
      { id: 3, title: "Bulnes", value: "bulnes" },
      { id: 4, title: "San Diego", value: "diego" },
      { id: 5, title: "Parque O'Higgins", value: "o'higgins" },
      { id: 6, title: "Parque Almagro", value: "almagro" },
      { id: 7, title: "Barrio Diez de Julio", value: "julio" },
      { id: 8, title: "Bogotá - Sierra Bella", value: "sierra" },
      { id: 9, title: "Barrio Yungay", value: "yungay" },
      { id: 10, title: "Barrio Brasil", value: "brasil" },
      { id: 11, title: "Barrio República", value: "república" },
      { id: 12, title: "Club Hípico", value: "hípico" },
      { id: 13, title: "Franklin - Biobío", value: "franklin" },
      { id: 14, title: "Parque Los Reyes", value: "reyes" },
      { id: 15, title: "San Borja", value: "borja" },
      { id: 16, title: "Barrio Meiggs", value: "meiggs" },
      { id: 17, title: "Lastarria", value: "lastarria" },
      { id: 18, title: "Ejército Toesca", value: "toesca" },
    ],
  },
  {
    city: "providencia",
    areas: [
      { id: 1, title: "Barrio Italia", value: "italia" },
      { id: 2, title: "Bellavista", value: "bellavista" },
      { id: 3, title: "Campus Oriente", value: "oriente" },
      { id: 4, title: "Inés de Suárez", value: "inés" },
      { id: 5, title: "Las Lilas", value: "lilas" },
      { id: 6, title: "Los Leones", value: "leones" },
      { id: 7, title: "Manuel Montt", value: "montt" },
      { id: 8, title: "Metro Bilbao", value: "bilbao" },
      { id: 9, title: "Metro Tobalaba", value: "tobalaba" },
      { id: 10, title: "Pedro de Valdivia", value: "valdivia" },
      { id: 11, title: "Pedro de Valdivia Norte", value: "norte" },
      { id: 12, title: "Plaza Italia", value: "plaza" },
      { id: 13, title: "Salvador", value: "salvador" },
      { id: 14, title: "Mall Costanera", value: "costanera" },
    ],
  },
  {
    city: "vitacura",
    areas: [
      { id: 1, title: "Borde Río - Casa Piedra", value: "piedra" },
      { id: 2, title: "Estadio Croata", value: "croata" },
      { id: 3, title: "Estadio Manquehue", value: "manquehue" },
      { id: 4, title: "Jardín Del Este", value: "este" },
      { id: 5, title: "Juan XXIII", value: "juan" },
      { id: 6, title: "La Llavería", value: "llavería" },
      { id: 7, title: "Lo Curro", value: "curro" },
      { id: 8, title: "Nuestra Señora del Rosario", value: "rosario" },
      { id: 9, title: "Parque Bicentenario", value: "bicentenario" },
      { id: 10, title: "Pío XI", value: "pío" },
      { id: 11, title: "Santa María de Manquehue", value: "santa" },
      { id: 12, title: "Tabancura", value: "tabancura" },
      { id: 13, title: "Villa El Dorado", value: "dorado" },
    ],
  },
  {
    city: "maipú",
    areas: [
      { id: 1, title: "Arauco Maipú", value: "arauco" },
      { id: 2, title: "Avenida Lumpen", value: "lumpen" },
      { id: 3, title: "El Descanso", value: "descanso" },
      { id: 4, title: "El Rosal", value: "rosal" },
      { id: 5, title: "Hospital El Carmen", value: "carmen" },
      { id: 6, title: "Metro del Sol", value: "sol" },
      { id: 7, title: "Metro Las Parcelas", value: "parcelas" },
      { id: 8, title: "Metro Santiago Bueras", value: "bueras" },
      { id: 9, title: "Nueva San Martín", value: "martín" },
      { id: 10, title: "Plaza de Maipú", value: "plaza" },
      { id: 11, title: "Villa Lo Errázuriz", value: "errázuriz" },
    ],
  },
];

module.exports = AREAS
