version: "3.9"
services:
  backend-commercialcity:
    build: . #ubicacion del archivo Dockerfile
    ports: 
      - "5000:5000"
    env_file:
      - .env
    links: 
      - mongodb-commercialcity
  mongodb-commercialcity:
    image: mongo
    env_file:
      - .env
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USER:$MONGO_PASSWORD@mongodb-commercialcity:27017/